brand=['Assaz', 'Azzaro', 'Bentley', 'Beverly Hills','Birraci', 'Boucheron', 'Burberry'
       , 'Bvlgari', 'Cacharel', 'Calvin Klein', 'Carolina Herrera', 'Cartier', 'Cerruti'
       , 'Chantal Thomass', 'Chloé', 'Chopard', 'Clinic', 'Collection Précieuse'
       , 'Collection premium', 'Collection privée'
       , 'Courrèges', 'Davidoff', 'Diesel', 'Dolce & Gabbana', 'Elie Saab'
       , 'Elie saab', 'Elizabeth Arden', 'Emanuel Ungaro', 'Emporio Armani'
       , 'Escada', 'Façonnable', 'Ferrari', 'Georges Rech', 'Giorgio Armani'
       , 'Giorgio Beverly Hills', 'Givenchy', 'Gris Montaigne', 'Grès', 'Gucci'
       , 'Guerlain', 'Guess', 'Hermès', 'Hugo Boss', 'Issey Miyake', 'J.T. Dupont'
       , 'Jaguar', 'Jea', 'Jean Michel Cavada'
       , 'Jean Paul Gaultier', 'Jimmy Choo', 'Karl Lagerfeld', 'Kenzo', "Kera Queen's"
       , 'Korloff','Lacoste', 'Lalique', 'Lancôme', 'Lanvin', 'Leonard'
       , 'Lolita Lempicka', 'M. Micaleff', 'M. Micallef', 'MAH', 'Maison Lazaar', 'Maison de la Vanille'
       , 'Maissa', 'Mancera', 'Marc Jacobes', 'Mauboussin', 'Micaleff'
       , 'Micallef', 'Montale','Montana', 'Montblanc', 'Mugler', 'Nina Ricci'
       , 'Paco Rabanne','Parfums de Niche', 'Pascal Morabito'
       , 'Prada','Prohair', 'RP', 'Reminiscence', 'Roberto Cavali', 'Rochas'
       , 'ST dupont', 'Scuderia Ferrari','Sélection Privé', 'Ted Lapidus'
       , 'The House Of Oud', 'The House of Wood', 'Tiziana Terenzi', 'Van Cleef & Arpels'
       , 'Versace', "Victoria's Secret", "Victoria's Secret Pink", "Women's Secret"]
